/* demandas.js */
window.DEMANDAS = [
  {
    "item": 1,
    "regiao": "Limitrofe",
    "bairro": "Alto do Itapiraco",
    "logradouro": "Rua Jacarepagua",
    "servico": "Recape, Drenagem Profunda e Superficial",
    "extensao_total_m": 1300,
    "area_m2": 1925,
    "preco_total": null,
    "observacao": null,
    "lat": -2.517643,
    "lng":  -44.189192,
    "endereco_consulta": "Rua Jacarepagua, Alto do Itapiraco, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Jacarepagua%2C%20Alto%20do%20Itapiraco%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 2,
    "regiao": "Limitrofe",
    "bairro": "Alto do Turú/ Recanto turu",
    "logradouro": "Rua dos Engenheiros",
    "servico": "Recape, Drenagem Profunda e Superficial",
    "extensao_total_m": 150,
    "area_m2": 825,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5124537,
    "lng":  -44.2028331,
    "endereco_consulta": "Rua dos Engenheiros, Alto do Turú/ Recanto turu, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20dos%20Engenheiros%2C%20Alto%20do%20Tur%C3%BA/%20Recanto%20turu%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 3,
    "regiao": "Limitrofe",
    "bairro": "Alto do Turú/ Recanto turu",
    "logradouro": "Rua Santo Antonio",
    "servico": "Recape, Drenagem Profunda e Superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5051394,
    "lng": -44.1845005,
    "endereco_consulta": "Rua Santo Antonio, Alto do Turú/ Recanto turu, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Santo%20Antonio%2C%20Alto%20do%20Tur%C3%BA/%20Recanto%20turu%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 4,
    "regiao": "Limitrofe",
    "bairro": "Alto do Turú/ Recanto turu",
    "logradouro": "Rua Senador Jose",
    "servico": "Recape, Drenagem Profunda e Superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat": -2.514949,
    "lng": -44.201873,
    "endereco_consulta": "Rua Senador Jose, Alto do Turú/ Recanto turu, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Senador%20Jose%2C%20Alto%20do%20Tur%C3%BA/%20Recanto%20turu%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 5,
    "regiao": "Limitrofe",
    "bairro": "Alto do Turú/ Recanto turu",
    "logradouro": "Rua São Jose",
    "servico": "Recape, Drenagem Profunda e Superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5133781,
    "lng": -44.1880940,
    "endereco_consulta": "Rua São Jose, Alto do Turú/ Recanto turu, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Jose%2C%20Alto%20do%20Tur%C3%BA/%20Recanto%20turu%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 6,
    "regiao": "Limitrofe",
    "bairro": "Alto do Turú/ Recanto turu",
    "logradouro": "Rua 3",
    "servico": "Recape, Drenagem Profunda e Superficial",
    "extensao_total_m": 500,
    "area_m2": 3000,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5316572,
    "lng": -44.1878945,
    "endereco_consulta": "Rua 3, Alto do Turú/ Recanto turu, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%203%2C%20Alto%20do%20Tur%C3%BA/%20Recanto%20turu%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 7,
    "regiao": "Limitrofe",
    "bairro": "Araçagy",
    "logradouro": "Rua Itabaiana",
    "servico": "Bloquete e Drenagem Superficial",
    "extensao_total_m": 650,
    "area_m2": 2282.5,
    "preco_total": null,
    "observacao": null,
    "lat": -2.493361,
    "lng": -44.200012,
    "endereco_consulta": "Rua Itabaiana, Araçagy, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Itabaiana%2C%20Ara%C3%A7agy%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 8,
    "regiao": "Limitrofe",
    "bairro": "Cohabiano",
    "logradouro": "Av.do Fio",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 1650,
    "area_m2": 9075,
    "preco_total": null,
    "observacao": null,
    "lat":  -2.5238151,
    "lng": -44.1903569,
    "endereco_consulta": "Av.do Fio, Cohabiano, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.do%20Fio%2C%20Cohabiano%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 9,
    "regiao": "Limitrofe",
    "bairro": "Itaguara",
    "logradouro": "Av.Central",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 600,
    "area_m2": 3300,
    "preco_total": null,
    "observacao": "Verificar cronograma do Estado - Tyago Freitas",
    "lat": -2.543232,
    "lng": -44.197663,
    "endereco_consulta": "Av.Central, Itaguara, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.Central%2C%20Itaguara%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 10,
    "regiao": "Limitrofe",
    "bairro": "Trizidela",
    "logradouro": "Rua da Pedreira",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 90,
    "area_m2": 450,
    "preco_total": null,
    "observacao": "Material no local, Falta Mao de Obra",
    "lat": -2.5397757,
    "lng": -44.1915914,
    "endereco_consulta": "Rua da Pedreira, Trizidela, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Pedreira%2C%20Trizidela%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 11,
    "regiao": "Limitrofe",
    "bairro": "Trizidela",
    "logradouro": "Rua Margaret",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": "Material no local, Falta Mao de Obra",
    "lat": -2.5505,
    "lng": -44.177,
    "endereco_consulta": "Rua Margaret, Trizidela, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Margaret%2C%20Trizidela%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 12,
    "regiao": "Limitrofe",
    "bairro": "Maioba do Jenipapeiro",
    "logradouro": "Av.Alonso Araujo",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 1100,
    "area_m2": 6600,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5109509,
    "lng": -44.1837996,
    "endereco_consulta": "Av.Alonso Araujo, Maioba do Jenipapeiro, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.Alonso%20Araujo%2C%20Maioba%20do%20Jenipapeiro%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 13,
    "regiao": "Limitrofe",
    "bairro": "Parque Araçagy / Miritiua",
    "logradouro": "Rua Araripina",
    "servico": "Recape e Drenagem Superficial",
    "extensao_total_m": 917,
    "area_m2": 5960.5,
    "preco_total": null,
    "observacao": null,
    "lat": -2.491123,
    "lng": -44.199266,
    "endereco_consulta": "Rua Araripina, Parque Araçagy / Miritiua, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Araripina%2C%20Parque%20Ara%C3%A7agy%20/%20Miritiua%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 14,
    "regiao": "Limitrofe",
    "bairro": "Parque Araçagy /Miritiua",
    "logradouro": "Rua Nova Esperança",
    "servico": "Pavimentação asfaltica, Drenagem Profunda e Superficial",
    "extensao_total_m": 2000,
    "area_m2": 12000,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Nova Esperança, Parque Araçagy /Miritiua, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Nova%20Esperan%C3%A7a%2C%20Parque%20Ara%C3%A7agy%20/Miritiua%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 15,
    "regiao": "Limitrofe",
    "bairro": "Parque das Palmeiras",
    "logradouro": "Rua da Mangueira",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 2110,
    "area_m2": 12660,
    "preco_total": null,
    "observacao": null,
    "lat": -2.4896233,
    "lng": -44.2048922,
    "endereco_consulta": "Rua da Mangueira, Parque das Palmeiras, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Mangueira%2C%20Parque%20das%20Palmeiras%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 16,
    "regiao": "Limitrofe",
    "bairro": "Parque Jair",
    "logradouro": "Av.Carlos Augusto",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 2000,
    "area_m2": 14000,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5078397,
    "lng": -44.1808098,
    "endereco_consulta": "Av.Carlos Augusto, Parque Jair, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.Carlos%20Augusto%2C%20Parque%20Jair%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 17,
    "regiao": "Limitrofe",
    "bairro": "Parque Vitória",
    "logradouro": "Rua Um (Rodão)",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 300,
    "area_m2": 1650,
    "preco_total": null,
    "observacao": null,
    "lat": -2.516545,
    "lng": -44.209469,
    "endereco_consulta": "Rua Um (Rodão), Parque Vitória, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Um%20%28Rod%C3%A3o%29%2C%20Parque%20Vit%C3%B3ria%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 18,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Rua Cheguevara",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 450,
    "area_m2": 2475,
    "preco_total": null,
    "observacao": null,
    "lat": -2.521132,
    "lng": -44.209115,
    "endereco_consulta": "Rua Cheguevara, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Cheguevara%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 19,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Rua O",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 150,
    "area_m2": 825,
    "preco_total": null,
    "observacao": null,
    "lat": -2.520872,
    "lng":  -44.207092,
    "endereco_consulta": "Rua O, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20O%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 20,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Rua P",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 150,
    "area_m2": 825,
    "preco_total": null,
    "observacao": null,
    "lat": -2.521408,
    "lng": -44.207474,
    "endereco_consulta": "Rua P, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20P%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 21,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Rua Q",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 120,
    "area_m2": 660,
    "preco_total": null,
    "observacao": null,
    "lat": -2.520093,
    "lng": -44.207820,
    "endereco_consulta": "Rua Q, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Q%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 22,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Rua R",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 120,
    "area_m2": 660,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua R, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20R%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 23,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Rua 15 de outubro",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 200,
    "area_m2": 1100,
    "preco_total": null,
    "observacao": null,
    "lat": -2.520746,
    "lng": -44.208180,
    "endereco_consulta": "Rua 15 de outubro, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2015%20de%20outubro%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 24,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Av 3 de Julho",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat": -2.520773,
    "lng": -44.210753,
    "endereco_consulta": "Av 3 de Julho, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av%203%20de%20Julho%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 25,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Av 05 de Dezembro",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 550,
    "area_m2": 3025,
    "preco_total": null,
    "observacao": null,
    "lat": -2.4918130,
    "lng": -44.1922090,
    "endereco_consulta": "Av 05 de Dezembro, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av%2005%20de%20Dezembro%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 26,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Av Moacir Feitosa",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 600,
    "area_m2": 3300,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5201086,
    "lng": -44.2045096,
    "endereco_consulta": "Av Moacir Feitosa, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av%20Moacir%20Feitosa%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 27,
    "regiao": "Limitrofe",
    "bairro": "Terra livre/ Canudos",
    "logradouro": "Av Karl Marx",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 550,
    "area_m2": 3025,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5203986,
    "lng": -44.2115569,
    "endereco_consulta": "Av Karl Marx, Terra livre/ Canudos, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av%20Karl%20Marx%2C%20Terra%20livre/%20Canudos%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 28,
    "regiao": "Vilas",
    "bairro": "Maiobinha",
    "logradouro": "Av.Maranguape",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 940,
    "area_m2": 6110,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5573380,
    "lng":  -44.2032516,
    "endereco_consulta": "Av.Maranguape, Maiobinha, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.Maranguape%2C%20Maiobinha%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 29,
    "regiao": "Vilas",
    "bairro": "Maiobinha",
    "logradouro": "Rua da Granja",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 720,
    "area_m2": 4320,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5573622,
    "lng": -44.2032588,
    "endereco_consulta": "Rua da Granja, Maiobinha, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Granja%2C%20Maiobinha%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 30,
    "regiao": "Vilas",
    "bairro": "Maiobinha",
    "logradouro": "Rua Claudio Licias",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 210,
    "area_m2": 1155,
    "preco_total": null,
    "observacao": null,
    "lat":  -2.5551728,
    "lng":  -44.1987959,
    "endereco_consulta": "Rua Claudio Licias, Maiobinha, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Claudio%20Licias%2C%20Maiobinha%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 31,
    "regiao": "Vilas",
    "bairro": "Maiobinha",
    "logradouro": "Rua da Macauba",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 195,
    "area_m2": 1072.5,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5588293,
    "lng": -44.1973540,
    "endereco_consulta": "Rua da Macauba, Maiobinha, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Macauba%2C%20Maiobinha%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 32,
    "regiao": "Vilas",
    "bairro": "Maiobinha",
    "logradouro": "Rua da Mangueira",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 200,
    "area_m2": 1100,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5581458,
    "lng": -44.2023235,
    "endereco_consulta": "Rua da Mangueira, Maiobinha, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Mangueira%2C%20Maiobinha%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 33,
    "regiao": "Vilas",
    "bairro": "Maiobinha",
    "logradouro": "Rua da Jaqueira",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 220,
    "area_m2": 1210,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5584222,
    "lng": -44.1975565,
    "endereco_consulta": "Rua da Jaqueira, Maiobinha, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Jaqueira%2C%20Maiobinha%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 34,
    "regiao": "Vilas",
    "bairro": "Vila Kiola",
    "logradouro": "Rua Rio Uma",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 200,
    "area_m2": 1200,
    "preco_total": null,
    "observacao": null,
    "lat":  -2.5568407,
    "lng":  -44.1856083,
    "endereco_consulta": "Rua Rio Uma, Vila Kiola, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Rio%20Uma%2C%20Vila%20Kiola%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 35,
    "regiao": "Vilas",
    "bairro": "Vila Kiola",
    "logradouro": "Princesa Ana",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 700,
    "area_m2": 4550,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5547787,
    "lng": -44.1803000,
    "endereco_consulta": "Princesa Ana, Vila Kiola, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Princesa%20Ana%2C%20Vila%20Kiola%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 36,
    "regiao": "Vilas",
    "bairro": "Vila Kiola/ kiolinha",
    "logradouro": "Rua do Carmo 1,2(campo)",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 80,
    "area_m2": 320,
    "preco_total": null,
    "observacao": null,
    "lat": -2.557819,
    "lng": -44.182879,
    "endereco_consulta": "Rua do Carmo 1,2(campo), Vila Kiola/ kiolinha, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20do%20Carmo%201%2C2%28campo%29%2C%20Vila%20Kiola/%20kiolinha%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 37,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua Paranã",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 800,
    "area_m2": 4400,
    "preco_total": null,
    "observacao": null,
    "lat": -2.556149,
    "lng":  -44.159713,
    "endereco_consulta": "Rua Paranã, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Paran%C3%A3%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 38,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Avenida São Raimundo/Rua 10",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 1000,
    "area_m2": 5500,
    "preco_total": null,
    "observacao": null,
    "lat": -2.560793,
    "lng": -44.168441,
    "endereco_consulta": "Avenida São Raimundo/Rua 10, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Avenida%20S%C3%A3o%20Raimundo/Rua%2010%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 39,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua da Alegria",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat": -2.565608,
    "lng": -44.173054,
    "endereco_consulta": "Rua da Alegria, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Alegria%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 40,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua 9",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat":  -2.5578728,
    "lng": -44.1649071,
    "endereco_consulta": "Rua 9, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%209%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 41,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua 15",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 1000,
    "area_m2": 5500,
    "preco_total": null,
    "observacao": null,
    "lat": -2.567290,
    "lng": -44.171911,
    "endereco_consulta": "Rua 15, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2015%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 42,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua 16",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 1200,
    "area_m2": 6600,
    "preco_total": null,
    "observacao": null,
    "lat": -2.567670,
    "lng": -44.168893,
    "endereco_consulta": "Rua 16, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2016%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 43,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua bom Jesus",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": -2.553110,
    "lng": -44.168734,
    "endereco_consulta": "Rua bom Jesus, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20bom%20Jesus%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 44,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua parque sabiá",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 300,
    "area_m2": 1650,
    "preco_total": null,
    "observacao": null,
    "lat": -2.567219,
    "lng": -44.167405,
    "endereco_consulta": "Rua parque sabiá, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20parque%20sabi%C3%A1%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 45,
    "regiao": "Vilas",
    "bairro": "Vila Sarney Filho  I & II",
    "logradouro": "Rua jardim botânico",
    "servico": "Pavimentação, Drenagem  Superficial",
    "extensao_total_m": 200,
    "area_m2": 1100,
    "preco_total": null,
    "observacao": null,
    "lat": -2.565810,
    "lng": -44.163927,
    "endereco_consulta": "Rua jardim botânico, Vila Sarney Filho  I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20jardim%20bot%C3%A2nico%2C%20Vila%20Sarney%20Filho%20%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 46,
    "regiao": "Vilas",
    "bairro": "J. Lima",
    "logradouro": "Rua Rio Grande do Sul",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 1400,
    "area_m2": 9100,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5665344,
    "lng": -44.1774704,
    "endereco_consulta": "Rua Rio Grande do Sul, J. Lima, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Rio%20Grande%20do%20Sul%2C%20J.%20Lima%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 47,
    "regiao": "Vilas",
    "bairro": "J. Lima",
    "logradouro": "Rua  1º de Maio",
    "servico": "Pavimentação asfaltica, Drenagem Profunda e  Superficial",
    "extensao_total_m": 500,
    "area_m2": 3000,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5665344,
    "lng": -44.1774704,
    "endereco_consulta": "Rua  1º de Maio, J. Lima, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20%201%C2%BA%20de%20Maio%2C%20J.%20Lima%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 48,
    "regiao": "Vilas",
    "bairro": "J. Lima",
    "logradouro": "Av. Maranhão",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 700,
    "area_m2": 4200,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Av. Maranhão, J. Lima, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.%20Maranh%C3%A3o%2C%20J.%20Lima%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 49,
    "regiao": "Vilas",
    "bairro": "J. Lima",
    "logradouro": "Rua 11",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 1600,
    "area_m2": 9600,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5665344,
    "lng": -44.1774704,
    "endereco_consulta": "Rua 11, J. Lima, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2011%2C%20J.%20Lima%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 50,
    "regiao": "Vilas",
    "bairro": "J. Lima",
    "logradouro": "Rua 13",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 1600,
    "area_m2": 3600,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5665344,
    "lng": -44.1774704,
    "endereco_consulta": "Rua 13, J. Lima, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2013%2C%20J.%20Lima%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 51,
    "regiao": "Vilas",
    "bairro": "J. Lima",
    "logradouro": "Rua 16",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 950,
    "area_m2": 3000,
    "preco_total": null,
    "observacao": "Falta Conclusão,Iniciado pelo Estado",
    "lat": -2.5665344,
    "lng": -44.1774704,
    "endereco_consulta": "Rua 16, J. Lima, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2016%2C%20J.%20Lima%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 52,
    "regiao": "Vilas",
    "bairro": "Vila São Luis",
    "logradouro": "Rua Paraíba",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 140,
    "area_m2": 770,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Paraíba, Vila São Luis, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Para%C3%ADba%2C%20Vila%20S%C3%A3o%20Luis%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 53,
    "regiao": "Vilas",
    "bairro": "Vila São Luis",
    "logradouro": "Rua do Acre",
    "servico": "Pavimentação asfaltica, Drenagem Profunda e  Superficial",
    "extensao_total_m": 350,
    "area_m2": 1925,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5457897,
    "lng": -44.2456451,
    "endereco_consulta": "Rua do Acre, Vila São Luis, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20do%20Acre%2C%20Vila%20S%C3%A3o%20Luis%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 54,
    "regiao": "Vilas",
    "bairro": "Vila São Luis",
    "logradouro": "Rua Rio de Janeiro",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 450,
    "area_m2": 2475,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5926931,
    "lng": -44.1958317,
    "endereco_consulta": "Rua Rio de Janeiro, Vila São Luis, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Rio%20de%20Janeiro%2C%20Vila%20S%C3%A3o%20Luis%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 55,
    "regiao": "Vilas",
    "bairro": "Vila São Luis",
    "logradouro": "Rua Pernambuco",
    "servico": null,
    "extensao_total_m": 140,
    "area_m2": 840,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5055329,
    "lng": -44.2198712,
    "endereco_consulta": "Rua Pernambuco, Vila São Luis, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Pernambuco%2C%20Vila%20S%C3%A3o%20Luis%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 56,
    "regiao": "Vilas",
    "bairro": "Vila São Luis",
    "logradouro": "Av. São Raimundo",
    "servico": "Pavimentação asfaltica, Drenagem Superficial",
    "extensao_total_m": 500,
    "area_m2": 3000,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5981581,
    "lng": -44.2266043,
    "endereco_consulta": "Av. São Raimundo, Vila São Luis, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.%20S%C3%A3o%20Raimundo%2C%20Vila%20S%C3%A3o%20Luis%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 57,
    "regiao": "Vilas",
    "bairro": "Vila Flamengo",
    "logradouro": "Rua Bahia",
    "servico": "Pavimentação asfaltica, Drenagem Profunda e  Superficial",
    "extensao_total_m": 750,
    "area_m2": 4500,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5652482,
    "lng": -44.1891512,
    "endereco_consulta": "Rua Bahia, Vila Flamengo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Bahia%2C%20Vila%20Flamengo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 58,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Av. Tropical",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 1500,
    "area_m2": 9000,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5703990,
    "lng": -44.1826132,
    "endereco_consulta": "Av. Tropical, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.%20Tropical%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 59,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Trav. Lagos",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 400,
    "area_m2": 2400,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Trav. Lagos, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Trav.%20Lagos%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 60,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Av. dos Lagos",
    "servico": "Pavimentação asfaltica, Drenagem Profunda e  Superficial",
    "extensao_total_m": 1600,
    "area_m2": 9600,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5492,
    "lng": -44.2058,
    "endereco_consulta": "Av. dos Lagos, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.%20dos%20Lagos%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 61,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Rua Cosme Damião",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 210,
    "area_m2": 1260,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Cosme Damião, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Cosme%20Dami%C3%A3o%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 62,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Rua Bom Jesus",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 200,
    "area_m2": 1200,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Bom Jesus, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Bom%20Jesus%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 63,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Rua da Gaivota",
    "servico": "Pavimentação asfaltica, Drenagem  Superficial",
    "extensao_total_m": 200,
    "area_m2": 1200,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua da Gaivota, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Gaivota%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 64,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Alameda São Francisco",
    "servico": "Pavimentação asfaltica, Drenagem Profunda e  Superficial",
    "extensao_total_m": 250,
    "area_m2": 1500,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Alameda São Francisco, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Alameda%20S%C3%A3o%20Francisco%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 65,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Av. do campo",
    "servico": "Pavimentação asfaltica, Drenagem Profunda e  Superficial",
    "extensao_total_m": 310,
    "area_m2": 1860,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Av. do campo, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Av.%20do%20campo%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 66,
    "regiao": "Vilas",
    "bairro": "Jardim Tropical I & II",
    "logradouro": "Rua Santa Helena",
    "servico": "Recape, Pavimentação asfaltica, Drenagem Profunda e  Superficial",
    "extensao_total_m": 1900,
    "area_m2": 11400,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Santa Helena, Jardim Tropical I & II, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Santa%20Helena%2C%20Jardim%20Tropical%20I%20%26%20II%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 67,
    "regiao": "Vilas",
    "bairro": "Residencial Piquezeiro/ Cedro",
    "logradouro": "Rua 9 de Abril",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 400,
    "area_m2": 2200,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5645,
    "lng": -44.2005,
    "endereco_consulta": "Rua 9 de Abril, Residencial Piquezeiro/ Cedro, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%209%20de%20Abril%2C%20Residencial%20Piquezeiro/%20Cedro%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 68,
    "regiao": "Vilas",
    "bairro": "Residencial Piquezeiro/ Cedro",
    "logradouro": "Rua Ipê",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Ipê, Residencial Piquezeiro/ Cedro, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Ip%C3%AA%2C%20Residencial%20Piquezeiro/%20Cedro%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 69,
    "regiao": "Vilas",
    "bairro": "Residencial Piquezeiro/ Cedro",
    "logradouro": "Rua das Palmeiras",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5828099,
    "lng": -44.1674245,
    "endereco_consulta": "Rua das Palmeiras, Residencial Piquezeiro/ Cedro, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20das%20Palmeiras%2C%20Residencial%20Piquezeiro/%20Cedro%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 70,
    "regiao": "Vilas",
    "bairro": "Residencial Piquezeiro/ Cedro",
    "logradouro": "Rua das Palmeiras 2",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5658,
    "lng": -44.2018,
    "endereco_consulta": "Rua das Palmeiras 2, Residencial Piquezeiro/ Cedro, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20das%20Palmeiras%202%2C%20Residencial%20Piquezeiro/%20Cedro%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 71,
    "regiao": "Vilas",
    "bairro": "Residencial Piquezeiro/ Cedro",
    "logradouro": "Tv Rua das Palmeiras",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 200,
    "area_m2": 1100,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5658,
    "lng": -44.2018,
    "endereco_consulta": "Tv Rua das Palmeiras, Residencial Piquezeiro/ Cedro, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tv%20Rua%20das%20Palmeiras%2C%20Residencial%20Piquezeiro/%20Cedro%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 72,
    "regiao": "Semi-Urbano",
    "bairro": "Pindaí",
    "logradouro": "Rua Sete de Setembro",
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": 500,
    "area_m2": 2750,
    "preco_total": null,
    "observacao": null,
    "lat":  -2.5558003,
    "lng": -44.1127380,
    "endereco_consulta": "Rua Sete de Setembro, Pindaí, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Sete%20de%20Setembro%2C%20Pinda%C3%AD%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 73,
    "regiao": "Semi-Urbano",
    "bairro": "Pindaí",
    "logradouro": "Rua São Luis",
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": 200,
    "area_m2": 1100,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua São Luis, Pindaí, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Luis%2C%20Pinda%C3%AD%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 74,
    "regiao": "Semi-Urbano",
    "bairro": "Pindaí",
    "logradouro": "Rua Dr Jose",
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": 1000,
    "area_m2": 5500,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Dr Jose, Pindaí, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Dr%20Jose%2C%20Pinda%C3%AD%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 75,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Rua mirititiua/Rua Principal",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 700,
    "area_m2": 4200,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua mirititiua/Rua Principal, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20mirititiua/Rua%20Principal%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 76,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Rua Raimundo Genesio/ Rua Principal",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 450,
    "area_m2": 2700,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Raimundo Genesio/ Rua Principal, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Raimundo%20Genesio/%20Rua%20Principal%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 77,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Tv Mirititiua",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 150,
    "area_m2": 900,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Tv Mirititiua, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tv%20Mirititiua%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 78,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Rua 17 de Agosto",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 240,
    "area_m2": 1440,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua 17 de Agosto, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2017%20de%20Agosto%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 79,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Rua 12 de Março",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 270,
    "area_m2": 1755,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua 12 de Março, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%2012%20de%20Mar%C3%A7o%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 80,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Tv do Campo",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 100,
    "area_m2": 500,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Tv do Campo, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tv%20do%20Campo%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 81,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Rua da Salina",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 70,
    "area_m2": 350,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua da Salina, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Salina%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 82,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Rua Cap Raimundo Leite",
    "servico": "Recape, Drenagem Superficial",
    "extensao_total_m": 600,
    "area_m2": 3300,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Cap Raimundo Leite, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Cap%20Raimundo%20Leite%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 83,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Tv Cap Raimundo Leite",
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": 170,
    "area_m2": 850,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Tv Cap Raimundo Leite, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tv%20Cap%20Raimundo%20Leite%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 84,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Tv Iomar Carvalho",
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": 180,
    "area_m2": 900,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Tv Iomar Carvalho, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tv%20Iomar%20Carvalho%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 85,
    "regiao": "Sede",
    "bairro": "Vila Alcione Gambarrinha/São Raimundo",
    "logradouro": "Rua s/n",
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": 350,
    "area_m2": 1925,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua s/n, Vila Alcione Gambarrinha/São Raimundo, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20s/n%2C%20Vila%20Alcione%20Gambarrinha/S%C3%A3o%20Raimundo%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 86,
    "regiao": "Sede",
    "bairro": "J camara 2",
    "logradouro": null,
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": null,
    "area_m2": 0,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "J camara 2, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=J%20camara%202%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 87,
    "regiao": "Sede",
    "bairro": "J camara 2",
    "logradouro": null,
    "servico": "Pavimentação asfaltica, Drenagem superficial",
    "extensao_total_m": null,
    "area_m2": 0,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "J camara 2, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=J%20camara%202%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 88,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Rua São Pedro",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 100,
    "area_m2": 550,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5438,
    "lng": -44.1675,
    "endereco_consulta": "Rua São Pedro, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Pedro%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 89,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Rua da Amizade",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 100,
    "area_m2": 550,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5445,
    "lng": -44.1682,
    "endereco_consulta": "Rua da Amizade, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Amizade%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 90,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Rua da Colina",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 120,
    "area_m2": 660,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua da Colina, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Colina%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 91,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Rua 6 de Maio",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 100,
    "area_m2": 550,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua 6 de Maio, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%206%20de%20Maio%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 92,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Rua Dário Santos",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 300,
    "area_m2": 1650,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Dário Santos, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20D%C3%A1rio%20Santos%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 93,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Rua São Simão",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 100,
    "area_m2": 550,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua São Simão, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Sim%C3%A3o%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 94,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Travessa Antônio Dino",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 150,
    "area_m2": 825,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Travessa Antônio Dino, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Travessa%20Ant%C3%B4nio%20Dino%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 95,
    "regiao": "Sede",
    "bairro": "Joao Cadal",
    "logradouro": "Rua Nair Deolany",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Nair Deolany, Joao Cadal, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Nair%20Deolany%2C%20Joao%20Cadal%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 96,
    "regiao": "Sede",
    "bairro": "Vila dr Julinho",
    "logradouro": "Rua Santa Maria",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 200,
    "area_m2": 1100,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5432,
    "lng": -44.161,
    "endereco_consulta": "Rua Santa Maria, Vila dr Julinho, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Santa%20Maria%2C%20Vila%20dr%20Julinho%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 97,
    "regiao": "Sede",
    "bairro": "Vila dr Julinho",
    "logradouro": "Rua Fé em Deus",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 220,
    "area_m2": 1210,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Fé em Deus, Vila dr Julinho, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20F%C3%A9%20em%20Deus%2C%20Vila%20dr%20Julinho%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 98,
    "regiao": "Sede",
    "bairro": "Vila dr Julinho",
    "logradouro": "Rua da paz",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 350,
    "area_m2": 1925,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua da paz, Vila dr Julinho, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20paz%2C%20Vila%20dr%20Julinho%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 99,
    "regiao": "Sede",
    "bairro": "Vila dr Julinho",
    "logradouro": "Rua 2 de maio",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 400,
    "area_m2": 2200,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua 2 de maio, Vila dr Julinho, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%202%20de%20maio%2C%20Vila%20dr%20Julinho%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 100,
    "regiao": "Sede",
    "bairro": "Roseana Sarney",
    "logradouro": "Rua São João",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5625,
    "lng": -44.1142,
    "endereco_consulta": "Rua São João, Roseana Sarney, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Jo%C3%A3o%2C%20Roseana%20Sarney%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 101,
    "regiao": "Sede",
    "bairro": "Roseana Sarney",
    "logradouro": "Rua São José",
    "servico": "Pavimentação, Drenagem superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua São José, Roseana Sarney, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Jos%C3%A9%2C%20Roseana%20Sarney%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 102,
    "regiao": "Sede",
    "bairro": "Roseana Sarney",
    "logradouro": "Rua São Jorge",
    "servico": "Pavimentção, Drenagem Superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua São Jorge, Roseana Sarney, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Jorge%2C%20Roseana%20Sarney%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 103,
    "regiao": "Sede",
    "bairro": "Roseana Sarney",
    "logradouro": "Rua São Miguel",
    "servico": "Pavimentção, Drenagem Superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua São Miguel, Roseana Sarney, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Miguel%2C%20Roseana%20Sarney%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 104,
    "regiao": "Sede",
    "bairro": "Roseana Sarney",
    "logradouro": "Rua São Luis",
    "servico": "Pavimentção, Drenagem Superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5642,
    "lng": -44.116,
    "endereco_consulta": "Rua São Luis, Roseana Sarney, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20S%C3%A3o%20Luis%2C%20Roseana%20Sarney%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 105,
    "regiao": "Sede",
    "bairro": "Roseana Sarney",
    "logradouro": "Rua Nossa Senhora",
    "servico": "Pavimentção, Drenagem Superficial",
    "extensao_total_m": 250,
    "area_m2": 1375,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Rua Nossa Senhora, Roseana Sarney, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20Nossa%20Senhora%2C%20Roseana%20Sarney%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 106,
    "regiao": "Sede",
    "bairro": "Panaquatira",
    "logradouro": "Rua da Secretaria",
    "servico": "Pavimentção, Drenagem Superficial",
    "extensao_total_m": 700,
    "area_m2": 3850,
    "preco_total": null,
    "observacao": null,
    "lat": -2.5115,
    "lng": -44.0488,
    "endereco_consulta": "Rua da Secretaria, Panaquatira, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rua%20da%20Secretaria%2C%20Panaquatira%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  },
  {
    "item": 107,
    "regiao": "Sede",
    "bairro": "Sítio do Apicum",
    "logradouro": null,
    "servico": null,
    "extensao_total_m": null,
    "area_m2": 0,
    "preco_total": null,
    "observacao": null,
    "lat": null,
    "lng": null,
    "endereco_consulta": "Sítio do Apicum, São José de Ribamar - MA, Brasil",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=S%C3%ADtio%20do%20Apicum%2C%20S%C3%A3o%20Jos%C3%A9%20de%20Ribamar%20-%20MA%2C%20Brasil"
  }
];

// deixa disponível globalmente para o seu script principal usar
window.DEMANDAS = DEMANDAS;
